
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://yourkingnico.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/yourkingnico.github.io"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Nicholas Torres"
title: "{ Nick Torres }"
description: "Nick Torres' website"
keywords: "nick, nicholas, torres, nicolas, personal, jekyll, theme"
favicon: "../img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg2.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "There's always a bigger fish. - Qui Gon Jinn" 
  - text: "Did you just ruin poker night?"
  - text: " The world is changing, and we must change with it. - Ragnar Lothbrok"
  - text: "It's a trap! - Admiral Ackbar"
 
me-img: "/img/nick-fall16.JPG"
 
 
##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Portfolio #
########

enable-gesture-navigation: True

post-preview-words: 40

paginate: 5

email-share: True
fb-share: false
twitter-share: false
linkedin-share: false
reddit-share: false
google-plus-share: false
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: "yourkingnico"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/corps.jpg"
    date: "September 2016 - Today"
    description: "Began working with Ball State Digital Corps"
  - image: "/img/timeline/chem.png"
    date: "February 2016 - Today"
    description: "Began working with Ball State Department of Chemistry"
  - image: "/img/timeline/gradhs.jpg"
    date: "June 2014"
    description: "Graduated from Willowbrook High School"
  - image: "/img/timeline/books.png"
    date: "Janruary 2014 - May 2014"
    description: "Attended Devry University"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

#email: "njtorres@bsu.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb:
#author_blurb_image: ""

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/yourkingnico"
 

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: 
keybase-in-social: false
keybase-in-footer: false

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Portfolio: 'picks.html'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
